server:
   port: 80
   servlet: 
      context-path: /ln
      session:
         timeout: 30m
   tomcat: 
       uri-encoding: utf-8
       max-threads: 500
       basedir: F:\lnmf\tmp
   error:
      path: /error
   #keytool -genkey -alias tomcathttps -keyalg RSA -keysize 2048 -keystore scott.p12 -validity 365
   ssl:
      key-store: scott.p12
      key-alias: tomcathttps
      key-store-password: 123456

book:
  name: 三国演义
  author: 罗贯中
  price: 30

file:
  uploadFilePath: F://lnmf/upload/
  downloadFilePath: F://lnmf/upload/  