server:
   port: 8081
   servlet: 
      context-path: /ln
      session:
         timeout: 30m
   tomcat: 
       uri-encoding: utf-8
       max-threads: 500
       basedir: F:\lnmf\tmp
   error:
      path: /error
   #keytool -genkey -alias tomcathttps -keyalg RSA -keysize 2048 -keystore scott.p12 -validity 365
   ssl:
      key-store: scott.p12
      key-alias: tomcathttps
      key-store-password: 123456

book:
  name: 三国演义
  author: 罗贯中
  price: 30

file:
  uploadFilePath: F://lnmf/upload/
  downloadFilePath: F://lnmf/upload/  


# master 数据源配置
master:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/travel?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 
    test-While-Idle: false
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config
# second 数据源配置
second:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/travel?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
# sql打印
logging:
  level:
    com.example.demo.dao : debug
# rabbitmq
spring:
  rabbitmq:
     host: localhost
     port: 5672
     username: test
     password: test
     virtual-host: /
     #listener:
       # type: simple
        #simple:
         # default-requeue-rejected: false
         # acknowledge-mode: manual
     publisher-confirms: true 
     publisher-returns: true
     #template:
         # mandatory: true